# Generated by Django 3.1.7 on 2021-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_choice', models.CharField(choices=[('Citizenship', (('citizenship_application', 'Citizenship application'), ('citizenship_declaration', 'Citizenship declaration'), ('citizenship_release', 'Release'), ('citizenship_maarianhamina', 'Ahvenanmaa/Maarianhamina: Citizenship matters'))), ('Residence', (('rp_work', 'Work'), ('rp_family', 'Family'), ('rp_studies', 'Studies'), ('rp_other_grounds', 'Other grounds'), ('rp_permanent', 'Permanent'), ('rp_renewal', 'Renewal')))], max_length=55)),
                ('office_choice', models.CharField(choices=[('helsinki_kaenkuja', 'Helsinki : K'), ('helsinki_malmi', 'Helsinki : M'), ('kuopio', 'Kuopio'), ('lahti', 'Lahti'), ('lappeenranta', 'Lappeenranta'), ('oulu', 'Oulu'), ('rovaniemi', 'Rovaniemi'), ('tampere', 'Tampere'), ('turku', 'Turku'), ('vaasa', 'Vaasa')], max_length=55)),
                ('to_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
